name: Dedupe
description: Determine whether workflows/jobs/steps can be skipped based on the modified files.

inputs:
  github_token:
    description: The Github authentication token.
    required: true
  ignore:
    description: Whether to ignore the determination. Used to conditionally force something to run even if it's skippable.
    required: false
    default: "false"
  paths:
    description: A YAML sequence of paths to include in the determination.
    required: false
    default: ""
  paths_ignore:
    description: A YAML sequence of paths to exclude from the determination
    required: false
    default: ""
  paths_named:
    description: A YAML mapping with named `paths`/`paths_ignore` conditions. Used to determine skippability for e.g., multiple jobs/steps in a workflow.
    required: false
    default: ""

outputs:
  should_skip:
    description: Whether the run should be skipped.
    value: ${{ inputs.ignore != 'false' && 'true' || steps.evaluate.outputs.should_skip }}
  named:
    description: Whether each named condition run should be skipped.
    value: ${{ inputs.ignore == 'true' && '{}' || steps.evaluate.outputs.paths_result }}

runs:
  using: composite
  steps:
    - name: Set paths in env
      if: ${{ inputs.ignore == 'false' }}
      run: |
        echo "PATHS=$(echo "$(cat <<EOF
        ${{ inputs.paths || '[]' }}
        EOF
        )" | yq -o=json -I=0)" >> $GITHUB_ENV
      shell: bash

    - name: Set paths_ignore in env
      if: ${{ inputs.ignore == 'false' }}
      run: |
        echo "PATHS_IGNORE=$(echo "$(cat <<EOF
        ${{ inputs.paths_ignore || '[]' }}
        EOF
        )" | yq -o=json -I=0)" >> $GITHUB_ENV
      shell: bash

    - name: Set paths_named in env
      if: ${{ inputs.ignore == 'false' }}
      run: |
        echo "PATHS_NAMED=$(echo "$(cat <<EOF
        ${{ inputs.paths_named || '{}' }}
        EOF
        )" | yq '.. style="flow"')" >> $GITHUB_ENV
      shell: bash

    - name: Evaluate conditions
      id: evaluate
      uses: fkirc/skip-duplicate-actions@04a1aebece824b56e6ad6a401d015479cd1c50b3
      if: ${{ inputs.ignore == 'false' }}
      with:
        cancel_others: true
        concurrent_skipping: never
        github_token: ${{ inputs.github_token }}
        paths: ${{ env.PATHS }}
        paths_ignore: ${{ env.PATHS_IGNORE }}
        paths_filter: ${{ env.PATHS_NAMED }}
        skip_after_successful_duplicate: true
        skip_summary: true
